worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: false

server-port: 8080
secdist-path: /home/houdini/Cpp/soc_net_aut/configs/secure_data.json
#dbconnection: 'postgresql://soc_net_aut_user:password@localhost:5432/soc_net_auth_3c'
